version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # 将宿主机的 5000 端口映射到容器内的 80 端口
    ports: 
      - "5000:80"

    # 将 web 服务的目录（.）下的文件 挂载到容器工作目录 /app 下
    # 这样可以在宿主机修改代码后，容器内会同步更新
    volumes: 
      - .:/app

    environment:
      - ENV_STATE=${ENV_STATE}
      - DATABASE_URL=${DATABASE_URL}
      - LOGTAIL_API_KEY=${LOGTAIL_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    
    # 使用的镜像名称
    image: krismile98/fastapi-rest-api:1.0
